language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

before_script:
  - node --version
  - npm --version

script:
  - npm test

matrix:
  fast_finish: true
